In [ ]:
#Array operations

In [ ]:
#arithametic operations

In [1]:
import numpy as np

In [3]:
a1=np.array([1,2,3,4,5,6])
a2=np.array([7,8,9,10,11,12])
a1+a2

array([ 8, 10, 12, 14, 16, 18])

In [5]:

arr2=a1-a2
arr2

array([-6, -6, -6, -6, -6, -6])

In [8]:
arr3=a1*a2
arr3

array([ 7, 16, 27, 40, 55, 72])

In [11]:
arr4=a1/a2
arr4

array([0.14285714, 0.25      , 0.33333333, 0.4       , 0.45454545,
       0.5       ])

In [14]:
a1//a2

array([0, 0, 0, 0, 0, 0])

In [ ]:
#Broad Casting

In [16]:
l=[1,2,3,4,5]
arr=np.array(l)
arr+10

array([11, 12, 13, 14, 15])

In [ ]:
#Deep and Shallow copy

In [ ]:
#Matrix operation

In [17]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[6,7],[8,9]])
mat1

array([[1, 2],
       [3, 4]])

In [18]:
mat2

array([[6, 7],
       [8, 9]])

In [19]:
mat1*mat2

array([[ 6, 14],
       [24, 36]])

In [23]:
mat1 @ mat2

array([[22, 25],
       [50, 57]])

In [24]:
np.dot(mat1,mat2)

array([[22, 25],
       [50, 57]])

In [25]:
mat1.T

array([[1, 3],
       [2, 4]])

In [ ]:
#stacking Arrays

In [ ]:
#you can't stack two matrixs

In [27]:
#vertical stack
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [28]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
#spliting Array 

In [32]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [35]:
z=np.vsplit(c,4)
for i in z:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
