In [8]:
 import numpy as np

In [11]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [15]:
a =[1,2,3.4,'numpy']
a

[1, 2, 3.4, 'numpy']

In [14]:
np.array(a)

array(['1', '2', '3', '4', 'numpy'], dtype='<U21')

In [16]:
l=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [18]:
np.array(l)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
# Array generations

In [21]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [23]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [24]:
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
arr=np.ones((4,9))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# Random Generation function

In [29]:
np.random.rand(10) #normalization

array([0.86419063, 0.77143222, 0.44636796, 0.80311308, 0.18432699])

In [30]:
np.random.randn(10) #(3 -> -3)

array([ 0.71467322, -0.12733073, -0.00318704,  0.51836528,  0.19083966,
        0.41488222, -2.80898873,  0.49002459,  0.19704915, -0.6331999 ])

In [31]:
np.random.randint(6) #6 is limit of range

5

In [32]:
np.random.randint(5,15,100) #(start ,end , no.of)

array([ 8,  9, 13,  6, 12,  7,  6,  6,  9,  5, 11, 12,  7,  5,  5,  8,  6,
       13, 11, 12, 14,  7, 11, 14,  9,  7, 13,  5, 10,  9, 11, 12,  7,  5,
        9, 14,  8, 10,  5,  5, 12,  6,  7, 10, 14,  9, 14,  5, 13, 13, 10,
        5, 14, 12,  9,  7, 14, 14,  9,  9, 11, 10,  7,  5,  6,  8,  5,  7,
       13, 14,  7,  6, 11, 10,  5, 11,  5, 14, 11, 12, 14,  9, 12, 10, 12,
       11, 14,  9,  5,  6,  5, 12, 10,  6,  8,  5,  8,  7, 11, 14],
      dtype=int32)

In [ ]:
# Array Attributes

In [34]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr.shape

(3, 3)

In [36]:
arr.size

9

In [37]:
arr.dtype

dtype('int64')

In [ ]:
#ARRay methods

In [39]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr.min()

np.int64(1)

In [41]:
arr.max()

np.int64(9)

In [42]:
arr.sum()

np.int64(45)

In [43]:
np.sum(arr,axis=0) # row =1,column =0

array([12, 15, 18])

In [44]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [45]:
arr.mean()

np.float64(5.0)

In [46]:
arr.std()

np.float64(2.581988897471611)

In [47]:
arr.argmax() # return max number index position

np.int64(8)

In [48]:
arr.argmin()

np.int64(0)

In [49]:
#reshaping and resizinga

In [52]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [53]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [54]:
arr=arr.reshape(6,5)  # reszie

In [55]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [56]:
#Array operations

In [ ]:
#arrray indexing and sizing

In [57]:
arr =np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [58]:
arr[7]

np.int64(18)

In [59]:
arr[1:5]

array([12, 13, 14, 15])

In [62]:
arr_slice=arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [ ]:
#NUMPY iNDEXING AND SLICING OF MATRIX

In [63]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [65]:
arr[1,2]

np.int64(8)

In [67]:
s1=arr[0:2,1:3]
s1

array([[2, 3],
       [7, 8]])

In [71]:
s2=arr[3:6,3:5]
s2

array([[19, 20],
       [24, 25],
       [29, 30]])

In [72]:
s3=arr[0:6,2:3]
s3

array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28]])

In [ ]:
#Booleam Indexing

In [81]:
arr=np.arange(1,20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [82]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False])

In [83]:
arr=arr[bool_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [78]:
#Array operations

# 